### ISSUE TITLE
panic on mac

### ISSUE THREAD

**Issue by ringtail** [byrnedo/dockdash#2]
Dockdash - Interactive realtime container inspector

┌%CPU───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                   │
│                                                                                                                                                   │
│                                                                                                                                                   │
│                                                                                                                                                   │
│                                                                                                                                                   │
│                                                                                                                                                   │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌%MEM───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                   │
│                                                                                                                                                   │
│                                                                                                                                                   │
│                                                                                                                                                   │
│                                                                                                                                                   │
│                                                                                                                                                   │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌Name───────────────────────────────┐┌Image─────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└───────────────────────────────────┘└──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘panic: runtime error: invalid memory address or nil pointer dereference
                                                                       [signal 0xb code=0x1 addr=0x0 pc=0x967f9]

```
                                                                                                            goroutine 12 [running]:
                                                                                                                                   github.com/byrnedo/dockdash/docklistener.dockerEventRoutingRoutine(0xc820018d20, 0xc820018a80, 0xc820018ae0)
                                                                                            /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/docklistener/docklistener.go:98 +0x1099
                                    created by github.com/byrnedo/dockdash/docklistener.Init
                                                                                                /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/docklistener/docklistener.go:62 +0x224

                                           goroutine 1 [chan receive]:
                                                                      main.main()
                                                                                    /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/main.go:199 +0x90f

       goroutine 17 [syscall, locked to thread]:
                                                runtime.goexit()
                                                                    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

                                                                                                                   goroutine 5 [syscall]:
                                                                                                                                         os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
                                                               created by os/signal.init.1
                                                                                            /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

                                                                                                                                               goroutine 6 [select, locked to thread]:
                                 runtime.gopark(0x4c34b0, 0xc820030728, 0x415340, 0x6, 0x2fe18, 0x2)
                                                                                                        /usr/local/go/src/runtime/proc.go:185 +0x163
   runtime.selectgoImpl(0xc820030728, 0x0, 0x18)
                                                    /usr/local/go/src/runtime/select.go:392 +0xa64
                                                                                                  runtime.selectgo(0xc820030728)
                                                                                                                                    /usr/local/go/src/runtime/select.go:212 +0x12
                            runtime.ensureSigM.func1()
                                                        /usr/local/go/src/runtime/signal1_unix.go:227 +0x323
                                                                                                                runtime.goexit()
                                                                                                                                    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

                              goroutine 7 [select]:
                                                   github.com/nsf/termbox-go.Init.func1()
                                                                                            /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/Godeps/_workspace/src/github.com/nsf/termbox-go/api.go:87 +0x40c
                                                             created by github.com/nsf/termbox-go.Init
                                                                                                        /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/Godeps/_workspace/src/github.com/nsf/termbox-go/api.go:106 +0x8b9

                                                                              goroutine 8 [select]:
                                                                                                   github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
                            /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/Godeps/_workspace/src/github.com/nsf/termbox-go/api.go:321 +0x6b3
```

  github.com/gizak/termui.evtListen.func1()
                                            /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/Godeps/_workspace/src/github.com/gizak/termui/events.go:164 +0x24
                  created by github.com/gizak/termui.evtListen
                                                                /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/Godeps/_workspace/src/github.com/gizak/termui/events.go:172 +0x2b

```
                              goroutine 9 [select]:
                                                   main.main.func1()
                                                                        /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/main.go:108 +0x1343
created by main.main
                        /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/main.go:195 +0x8b5

                                                                                                    goroutine 11 [select]:
                                                                                                                          github.com/byrnedo/dockdash/docklistener.statsRenderingRoutine(0xc820018c00)
                                                    /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/docklistener/docklistener.go:154 +0x3cd
```

created by github.com/byrnedo/dockdash/docklistener.Init
                                                            /Users/zhongweilzw/go/src/github.com/byrnedo/dockdash/docklistener/docklistener.go:60 +0x1e6
       %

**Comment by byrnedo** [comment]
Think it's just a small fix. I'll push asap.

**Comment by byrnedo** [comment]
I pushed there. Also a new [release](https://github.com/byrnedo/dockdash/releases) 0.10 or 0.11 (updated to use newest gizak/termui and some other improvements). Please try! :)

**Comment by byrnedo** [comment]
Closing due to lack of activity
